name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-checks-basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.2
    with:
      working_directory: './example/basic'

  tf-checks-complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.2
    with:
      working_directory: './example/complete'